[package]
name = "project1"
version = "0.1.0"
authors = ["Isaac <isaacpro01@gmail.com"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
